---
title: "Example anisotropy analysis using Kdirectional"
author: "Tuomas Rajala"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
---
  
## Introduction
The package `Kdirectional` is a collection of tools for analysing the isotropy of 2- and 3-dimensional point patterns. This document shows how to use some of these tools by analysing an synthetic example pattern.

In this vignette we use the following packages:
```{r, include=FALSE}
library(spatstat)
library(Kdirectional)
library(ellipsoid)
library(sphere)
```

```{r, eval=FALSE}
library(spatstat)
library(Kdirectional)
library(ellipsoid)
library(sphere)
```



## Example patterns

```{r, cache=TRUE}
# Simulate Poisson line process, by Claudia:
#Poisson pattern with stripes of increased intensity, stationary case
set.seed(10)
f<-function(x,y){100*dnorm(x, mean=0.5, sd=0.03)}
pp<-rpoispp(200)
ppl1<-rpoispp(f, win=owin(c(-2,2), c(-2,2)))
ppl2<-rpoispp(f, win=owin(c(-2,2), c(-2,2)))
ppl3<-rpoispp(f, win=owin(c(-2,2), c(-2,2)))
#little cheating: position of stripes is deterministic
pplshift1<-shift(ppl1, vec=c(0,0))
pplshift2<-shift(ppl2, vec=c(0.6,0))
pplshift3<-shift(ppl3, vec=c(-0.2,0))
pplrot<-rotate(pplshift1, angle=pi/5)
pplrot2<-rotate(pplshift2, angle=pi/5)
pplrot3<-rotate(pplshift3, angle=pi/5)
pptot <- superimpose(pplrot, pplrot2, pplrot3, pp, W=owin(c(0,1),c(0,1)))
stripes <- pptot[square(1)]
```

```{r, cache=TRUE}
# Simulate geometrically anisotropic Strauss process:
# The transformation
R <- rotationMatrix(az = -pi/6)[1:2, 1:2]
compression_y <- 0.6
C <- diag( c( 1/compression_y, compression_y) )
M <- R %*% C
# Simulate Strauss in big window
Wobs <- as.owin(c(-1,1,-1,1))
Wsim <- affine(Wobs, solve(M))
regular_R <- 0.1
regular_gamma <- 0.1
set.seed(123)
regular_orig <- rStrauss(beta = 100, R = regular_R, gamma = regular_gamma, W = Wsim, expand = TRUE)
# This is the final observation
regular <- affine(regular_orig, M)[Wobs]
```

```{r, fig.width=10, fig.height=5}
plot(pats <- listof(regular=regular, Poisson_linear=stripes), main="Example 2D patterns")
```

# Fry points


```{r, fig.width=8, fig.height=4}
fry_reg <- fry_points(regular, border = F, double =T)
fry_clu <- fry_points(stripes, border = F, double =T)
# trim for figure
ok_reg <- fry_reg$fry_r < .6
ok_clu <- fry_clu$fry_r < 0.8
p_reg <- with(fry_reg, fry_r[ok_reg] * fry_units[ok_reg,])
p_clu <- with(fry_clu, fry_r[ok_clu] * fry_units[ok_clu,])
plotf <- function(x, xl, ...) plot(x, xlim = xl, ylim = xl, asp=1, ann=F, ...)
par(mfrow=c(1,2), mar=c(2,2,2,1))
plotf(p_reg, c(-1,1)*.4, pch=19, cex=.3); title("Regular")
plotf(p_clu, c(-1,1)*.5, pch="."); title("Clustered")
```


# Nearest neighbour summaries

```{r}
nn_orientation <- lapply(pats, function(x) nn_orientation_density(x, antipodal = FALSE, bw = 0.35))
nn_orientation2 <- lapply(pats, function(x) nn_orientation_density(x, antipodal = FALSE, bw = 0.7))
# compute angle distribution over increasing sector starting from 0.
epsilon <- seq(0, pi, l = 50)
directions <- angle_2_unit(epsilon)
nn_angle <- lapply(pats, function(x) nn_directional_angle_distribution(x, directions, epsilon, r = 0.1)   )
nn_angle2 <- lapply(pats, function(x) nn_directional_angle_distribution(x, directions, epsilon, r = 0.3)   )
# the range-wise distributions
dirs <- angle_2_unit(c(0, pi/4, pi/2, 3*pi/4))
f1 <- function(x, ...) nn_directional_distance_distribution(x, epsilon=pi/6, direction = dirs, ...)
nn_global <- lapply(pats, f1, type="global")
nn_local <- lapply(pats, f1, type="local")

```

```{r, fig.width=10, fig.height=10}
par(mfrow=c(4,2))
plot(nn_orientation$regular, type="l", main = "nn orientation density\nbw=0.35", ylim=c(0,.4))
lines(nn_orientation$Poisson_linear, col=2, lty=2)
legend("topright", lty=1:3, col=1:3, c(names(pats), "uniform") )
abline(h=1/(2*pi), lty=3, col=3)

plot(nn_orientation2$regular, type="l", main = "nn orientation density, double cone\nbw=0.7", ylim=c(0,.4))
lines(nn_orientation2$Poisson_linear, col=2, lty=2)

with(nn_angle$regular, plot(epsilon*2, est, type="l", main = "nn orientation distribution, increasing sector, r = 0.1", ylim=c(0,1), xlab="angle"))
with(nn_angle$Poisson_linear, lines(epsilon*2, est, col=2, lty=2))
legend("topleft", lty=1:3, col=1:3, c(names(pats), "uniform") )
abline(0, 1/(2*pi), lty=3, col=3)

with(nn_angle2$regular, plot(epsilon*2, est, type="l", main = "nn orientation distribution, increasing sector, r = 0.3", ylim=c(0,1), xlab="angle"))
with(nn_angle2$Poisson_linear, lines(epsilon*2, est, col=2, lty=2))
abline(0, 1/(2*pi), lty=3, col=3)

plot(nn_global$regular, main="Global G, regular", legpos=F)
plot(nn_global$Poisson_linear, main="Global G, clustered", legpos=F)
legend("bottomright", lty=1:4, col=1:4, expression(0, pi/4, pi, 3*pi/4))
plot(nn_local$regular, main="local G, regular", legpos=F)
plot(nn_local$Poisson_linear, main="local G, clustered", legpos = F)
legend("bottomright", lty=1:4, col=1:4, expression(0, pi/4, pi, 3*pi/4))
```



### References









